---

switches_files:
  - "/run/sysmonitor/history"
  - "/etc/sysctl.d/99-sysctl.conf"
  - "/etc/default/grub"
  - "/etc/cumulus/ports.conf"
  - "/etc/network/interfaces"
  - "/etc/ntp.conf"
  - "etc/frr/frr.conf"
